# Generated by Django 4.2.7 on 2026-03-04 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utility.storageClasses


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='giftPool/')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minWalletBalance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('liveDate', models.DateTimeField()),
                ('closingDate', models.DateTimeField()),
                ('isLocked', models.BooleanField(default=False)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift Pool',
                'verbose_name_plural': '2. Gift Pools',
                'ordering': ['-liveDate'],
            },
        ),
        migrations.CreateModel(
            name='PricePoolRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField()),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Pool Range',
                'verbose_name_plural': '3. Price Pool Ranges',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PricePoolStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomSize', models.PositiveSmallIntegerField()),
                ('winningNumbers', models.CharField(max_length=50)),
                ('video', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='pricePoolStream/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price Pool Stream',
                'verbose_name_plural': '1. Lottery Streams',
                'ordering': ['roomSize', 'winningNumbers'],
            },
        ),
        migrations.CreateModel(
            name='PricePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketCount', models.PositiveSmallIntegerField()),
                ('timeIntervalMin', models.PositiveSmallIntegerField()),
                ('isLocked', models.BooleanField(default=False)),
                ('isClosed', models.BooleanField(default=False)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lotteryManager.pricepoolrange')),
            ],
            options={
                'verbose_name': 'Price Pool',
                'verbose_name_plural': '4. Price Pools',
            },
        ),
        migrations.CreateModel(
            name='PricePoolGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('pricePool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryManager.pricepool')),
            ],
            options={
                'verbose_name': 'Price Pool Gift',
                'verbose_name_plural': 'Price Pool Gifts',
                'ordering': ['rank'],
                'unique_together': {('pricePool', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='GiftPoolWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('giftPool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryManager.giftpool')),
            ],
            options={
                'verbose_name': 'Gift Pool Winner',
                'verbose_name_plural': 'Gift Pool Winners',
                'ordering': ['rank'],
                'unique_together': {('giftPool', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='GiftPoolGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('giftPool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteryManager.giftpool')),
            ],
            options={
                'verbose_name': 'Gift Pool Gift',
                'verbose_name_plural': 'Gift Pool Gifts',
                'ordering': ['rank'],
                'unique_together': {('giftPool', 'rank')},
            },
        ),
    ]
