# Generated by Django 4.2.7 on 2026-03-04 12:32

from django.db import migrations, models
import django.db.models.deletion
import utility.storageClasses


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('C', 'Common'), ('L', 'Lottery')], max_length=1)),
                ('category', models.CharField(choices=[('S', 'Cockfight'), ('P', 'Promotion'), ('L', 'Lottery'), ('W', 'Wallet'), ('V', 'Learning Videos')], max_length=1)),
                ('banner', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='banners/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': '1. Banners',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='highlight_thumbnails/')),
                ('video', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='highlight_videos/')),
                ('category', models.CharField(choices=[('C', 'Cockfight'), ('L', 'Lottery')], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': '3. Highlights',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('T', 'Telugu'), ('H', 'Hindi'), ('E', 'English'), ('I', 'Tamil'), ('M', 'Malayalam')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='learning_thumbnails/')),
                ('video', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='learning_videos/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Video',
                'verbose_name_plural': '4. Learning Videos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='promotional_products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('strikePrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minWalletBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': '5. Giveaway Products',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'Is App Under Maintenance?'), ('B', 'Is Cock-Fight Under Maintenance?'), ('C', 'Is Lottery Under Maintenance?'), ('D', 'Is Cricket Under Maintenance?'), ('E', 'Whatsapp Link'), ('F', 'Telegram Link'), ('G', 'Youtube Link'), ('H', 'Facebook Link'), ('I', 'Instagram Link'), ('J', 'Min Deposit Value'), ('K', 'Monthly Subscription Cost'), ('L', 'Min Balance To Watch Live'), ('M', 'Monthly Free Withdrawal'), ('N', 'Additional Withdrawal Commession %'), ('O', 'Scrolling Promotion Text'), ('P', 'Gift Pool Intro Video'), ('Q', 'Price Pool Intro Video'), ('R', 'China Cockfight A Upper Ratio'), ('S', 'China Cockfight B Upper Ratio'), ('T', 'China Cockfight Draw Upper Ratio'), ('U', 'China Cockfight A Lower Ratio'), ('V', 'China Cockfight B Lower Ratio'), ('W', 'China Cockfight Draw Lower Ratio'), ('X', "Auto Match Secret Access Line Key (DON'T TOUCH)")], max_length=1, unique=True)),
                ('actionValue', models.CharField(max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['action'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('F', 'Cockfight'), ('L', 'Lottery'), ('C', 'Cricket')], max_length=1)),
                ('status', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='status/')),
                ('isActive', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': '2. Statuses',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Delivered'), ('R', 'Rejected'), ('F', 'Refunded')], default='P', max_length=1)),
                ('deliveryTo', models.CharField(max_length=50)),
                ('deliveryPhoneNumber', models.CharField(max_length=10)),
                ('deliveryAddress', models.CharField(max_length=800)),
                ('deducted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
            options={
                'verbose_name': 'Product Order',
                'verbose_name_plural': '6. Product Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
