# Generated by Django 4.2.7 on 2026-03-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('S', 'Cockfight'), ('P', 'Promotion'), ('D', 'Dice Play'), ('W', 'Wallet'), ('V', 'Learning Videos')], max_length=1),
        ),
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('C', 'Common'), ('D', 'Dice Play')], max_length=1),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='category',
            field=models.CharField(choices=[('C', 'Cockfight'), ('D', 'Dice Play')], max_length=1),
        ),
        migrations.AlterField(
            model_name='setting',
            name='action',
            field=models.CharField(choices=[('A', 'Is App Under Maintenance?'), ('B', 'Is Cock-Fight Under Maintenance?'), ('C', 'Is Dice Play Under Maintenance?'), ('D', 'Is Cricket Under Maintenance?'), ('E', 'Whatsapp Link'), ('F', 'Telegram Link'), ('G', 'Youtube Link'), ('H', 'Facebook Link'), ('I', 'Instagram Link'), ('J', 'Min Deposit Value'), ('K', 'Monthly Subscription Cost'), ('L', 'Min Balance To Watch Live'), ('M', 'Monthly Free Withdrawal'), ('N', 'Additional Withdrawal Commession %'), ('O', 'Scrolling Promotion Text'), ('P', 'Gift Pool Intro Video'), ('Q', 'Price Pool Intro Video'), ('R', 'China Cockfight A Upper Ratio'), ('S', 'China Cockfight B Upper Ratio'), ('T', 'China Cockfight Draw Upper Ratio'), ('U', 'China Cockfight A Lower Ratio'), ('V', 'China Cockfight B Lower Ratio'), ('W', 'China Cockfight Draw Lower Ratio'), ('X', "Auto Match Secret Access Line Key (DON'T TOUCH)")], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='category',
            field=models.CharField(choices=[('F', 'Cockfight'), ('D', 'Dice Play'), ('C', 'Cricket')], max_length=1),
        ),
    ]
