# Generated by Django 4.2.7 on 2026-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_banner_category_alter_banner_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='action',
            field=models.CharField(choices=[('A', 'Is App Under Maintenance?'), ('B', 'Is Cock-Fight Under Maintenance?'), ('C', 'Is Dice Play Under Maintenance?'), ('D', 'Is Cricket Under Maintenance?'), ('E', 'Whatsapp Link'), ('F', 'Telegram Link'), ('G', 'Youtube Link'), ('H', 'Facebook Link'), ('I', 'Instagram Link'), ('J', 'Min Deposit Value'), ('K', 'Monthly Subscription Cost'), ('L', 'Min Balance To Watch Live'), ('M', 'Monthly Free Withdrawal'), ('N', 'Additional Withdrawal Commession %'), ('O', 'Scrolling Promotion Text'), ('P', 'Dice Play Intro Video'), ('R', 'China Cockfight A Upper Ratio'), ('S', 'China Cockfight B Upper Ratio'), ('T', 'China Cockfight Draw Upper Ratio'), ('U', 'China Cockfight A Lower Ratio'), ('V', 'China Cockfight B Lower Ratio'), ('W', 'China Cockfight Draw Lower Ratio'), ('X', "Auto Match Secret Access Line Key (DON'T TOUCH)")], max_length=1, unique=True),
        ),
    ]
