import { icon } from './icons.js?v=7';

export function escapeHtml(value='') { return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }
export function money(value=0) { return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(value)||0); }
export function dateTime(value) { if(!value)return 'Not set'; const date=new Date(value); return Number.isNaN(date.getTime())?escapeHtml(value):new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(date); }
export function safeUrl(value='') { try { const url=new URL(value,window.location.origin); return ['http:','https:'].includes(url.protocol)?url.href:'#'; } catch{return '#';} }
export function badge(value='') { const tone=String(value).toLowerCase().replace(/_/g,'-'); return `<span class="status status--${escapeHtml(tone)}">${escapeHtml(String(value).replace(/_/g,' '))}</span>`; }
export function button(label,{action='',tone='secondary',iconName='',type='button',extra='',disabled=false}={}) { const resolvedAction=action||(['Publish media','Save media'].includes(label)?'publish-media':type==='submit'?'submit-form':'');return `<button class="button button--${tone}" type="${type}" ${resolvedAction?`data-action="${resolvedAction}"`:''} ${extra} ${disabled?'disabled':''}>${iconName?icon(iconName,17):''}<span>${escapeHtml(label)}</span></button>`; }
export function empty(iconName,title,copy) { return `<div class="empty-state">${icon(iconName,28)}<strong>${escapeHtml(title)}</strong><p>${escapeHtml(copy)}</p></div>`; }
export function metric(iconName,label,value,detail,tone='gold') { return `<article class="metric-card"><span class="metric-card__icon metric-card__icon--${tone}">${icon(iconName,20)}</span><div><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong><p>${escapeHtml(detail)}</p></div></article>`; }
export function pageHeader(eyebrow,title,copy,action='') { return `<header class="page-header"><div><span>${escapeHtml(eyebrow)}</span><h1>${escapeHtml(title)}</h1><p>${escapeHtml(copy)}</p></div>${action}</header>`; }
export function field({name,label,value='',type='text',placeholder='',required=false,min='',max='',step='',wide=false,help='',disabled=false}) { return `<label class="form-field ${wide?'form-field--wide':''}"><span>${escapeHtml(label)}</span><input name="${escapeHtml(name)}" type="${escapeHtml(type)}" value="${escapeHtml(value)}" placeholder="${escapeHtml(placeholder)}" ${required?'required':''} ${disabled?'disabled':''} ${min!==''?`min="${escapeHtml(min)}"`:''} ${max!==''?`max="${escapeHtml(max)}"`:''} ${step!==''?`step="${escapeHtml(step)}"`:''}>${help?`<small>${escapeHtml(help)}</small>`:''}</label>`; }
export function mediaPicker({name,label,value='',kind='image',help='',required=false}) { const image=kind==='image';const accept=image?'image/png,image/jpeg,image/webp':'video/mp4,video/webm';const limits=image?'PNG, JPG or WebP · up to 5 MB':'MP4 or WebM · up to 250 MB';return `<fieldset class="media-picker form-field--wide"><legend>${escapeHtml(label)}</legend><div class="media-picker__options"><label><span>${icon('upload',17)}Upload from device</span><input name="${escapeHtml(name)}_file" type="file" accept="${accept}" ${required&&!value?'required':''}><small>${limits}</small></label><i>OR</i><label><span>${icon('link',17)}Use a media link</span><input name="${escapeHtml(name)}_url" type="text" value="${escapeHtml(value)}" placeholder="https://… or /uploads/…"><small>Paste a secure direct URL${image?' to the image':' or streaming source'}.</small></label></div>${value?`<div class="media-picker__current">${image?`<img src="${escapeHtml(value)}" alt="Current ${escapeHtml(label).toLowerCase()}">`:icon('live',18)}<span><small>Current source</small><strong>${escapeHtml(value)}</strong></span></div>`:''}${help?`<p>${escapeHtml(help)}</p>`:''}</fieldset>`; }
export function selectField({name,label,value='',options=[],wide=false}) { return `<label class="form-field ${wide?'form-field--wide':''}"><span>${escapeHtml(label)}</span><select name="${escapeHtml(name)}">${options.map(option=>{const [key,text]=Array.isArray(option)?option:[option,option];return `<option value="${escapeHtml(key)}" ${String(key)===String(value)?'selected':''}>${escapeHtml(text)}</option>`;}).join('')}</select></label>`; }
export function switchField(name,label,copy,checked=false) { return `<label class="switch-field"><span><strong>${escapeHtml(label)}</strong><small>${escapeHtml(copy)}</small></span><input name="${escapeHtml(name)}" type="checkbox" ${checked?'checked':''}><i></i></label>`; }
export function panel(title,eyebrow,content,actions='') { return `<section class="panel"><header class="panel__header"><div><small>${escapeHtml(eyebrow)}</small><h2>${escapeHtml(title)}</h2></div>${actions}</header>${content}</section>`; }
export function modal(title,eyebrow,content,{size='normal'}={}) { return `<div class="modal-backdrop" data-action="close-modal"><section class="modal modal--${size}" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title" data-modal-panel><header><div><small>${escapeHtml(eyebrow)}</small><h2 id="admin-modal-title">${escapeHtml(title)}</h2></div><button type="button" data-action="close-modal" aria-label="Close">${icon('close',20)}</button></header>${content}</section></div>`; }
export { icon };
