import os

AZURE_ACCOUNT_NAME = os.environ.get("AZURE_ACCOUNT_NAME")
AZURE_ACCOUNT_KEY = os.environ.get("AZURE_ACCOUNT_KEY")
AZURE_CONTAINER = os.environ.get("AZURE_CONTAINER")
AZURE_CONNECTION_STRING = os.environ.get("AZURE_CONNECTION_STRING")
if AZURE_ACCOUNT_NAME:
    AZURE_CUSTOM_DOMAIN = f"{AZURE_ACCOUNT_NAME}.blob.core.windows.net"
else:
    AZURE_CUSTOM_DOMAIN = None
