# Generated by Django 4.2.7 on 2026-03-04 12:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import utility.storageClasses


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoMatchPollingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runningAutoMatchId', models.PositiveBigIntegerField(null=True)),
                ('runningMatchRefId', models.CharField(blank=True, max_length=20, null=True)),
                ('matchNumber', models.CharField(max_length=5, null=True)),
                ('isNewMatchUpdated', models.BooleanField(blank=True, null=True)),
                ('isAcceptingBet', models.BooleanField(default=False)),
                ('liveUrl', models.URLField(null=True)),
                ('stampingUrl', models.URLField(null=True)),
                ('pastMatchRefId', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CockfightAutoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchTitle', models.CharField(max_length=120, null=True)),
                ('referanceId', models.CharField(max_length=15, null=True)),
                ('matchNumber', models.PositiveSmallIntegerField(null=True)),
                ('winTeam', models.PositiveSmallIntegerField(default=0)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
        migrations.CreateModel(
            name='CockfightMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('liveDate', models.DateTimeField(blank=True, null=True)),
                ('isLive', models.BooleanField(default=False)),
                ('isBettingEnabled', models.BooleanField(default=False)),
                ('youtubeLiveLink', models.CharField(blank=True, max_length=100, null=True)),
                ('promoVideo', models.FileField(blank=True, null=True, storage=utility.storageClasses.AzurePublicStorage(), upload_to='cockfightMatchPromo/')),
                ('teamAName', models.CharField(default='Meron', max_length=15)),
                ('teamBName', models.CharField(default='Wala', max_length=15)),
                ('teamAIcon', models.FileField(blank=True, null=True, storage=utility.storageClasses.AzurePublicStorage(), upload_to='cockfightMatchIcons/')),
                ('teamBIcon', models.FileField(blank=True, null=True, storage=utility.storageClasses.AzurePublicStorage(), upload_to='cockfightMatchIcons/')),
                ('minThresholdTeamA', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.75'), max_digits=3, null=True)),
                ('maxThresholdTeamA', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.85'), max_digits=3, null=True)),
                ('minThresholdTeamB', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.75'), max_digits=3, null=True)),
                ('maxThresholdTeamB', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.85'), max_digits=3, null=True)),
                ('minThresholdTeamDraw', models.DecimalField(blank=True, decimal_places=2, default=Decimal('3.00'), max_digits=4, null=True)),
                ('maxThresholdTeamDraw', models.DecimalField(blank=True, decimal_places=2, default=Decimal('5.00'), max_digits=4, null=True)),
                ('winTeam', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('isWinnerDeclared', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cockfight Match',
                'verbose_name_plural': '2. Cockfight Matches',
                'ordering': ['liveDate', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CockfightMatchBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.CharField(db_index=True, max_length=25)),
                ('matchType', models.CharField(choices=[('A', 'Auto Match'), ('M', 'Manual Match')], db_index=True, max_length=1)),
                ('betTeam', models.PositiveSmallIntegerField(db_index=True)),
                ('amount', models.PositiveSmallIntegerField()),
                ('betRatio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('matchWinStatus', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('createdDate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': '1. Zones',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='cockfightMa_is_acti_2d8357_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchPremiumHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('video', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='matchPremiumHighlights/')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cockfightManager.cockfightmatch')),
            ],
        ),
    ]
