# Generated by Django 4.2.7 on 2026-03-04 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cockfightManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockfightmatchbet',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cockfightmatch',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cockfightManager.zone'),
        ),
        migrations.AddIndex(
            model_name='cockfightautomatch',
            index=models.Index(fields=['processed'], name='cockfightMa_process_131e04_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightautomatch',
            index=models.Index(fields=['referanceId'], name='cockfightMa_referan_1bb61b_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatchbet',
            index=models.Index(fields=['matchType', 'matchId'], name='cockfightMa_matchTy_bbce7a_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatchbet',
            index=models.Index(fields=['customer', 'matchWinStatus'], name='cockfightMa_custome_f4ba74_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatchbet',
            index=models.Index(fields=['matchType', 'matchId', 'betTeam'], name='cockfightMa_matchTy_8382da_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatch',
            index=models.Index(fields=['zone', 'liveDate'], name='cockfightMa_zone_id_eeef66_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatch',
            index=models.Index(fields=['isLive'], name='cockfightMa_isLive_390aec_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatch',
            index=models.Index(fields=['isWinnerDeclared'], name='cockfightMa_isWinne_217a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatch',
            index=models.Index(fields=['processed'], name='cockfightMa_process_6098b1_idx'),
        ),
        migrations.AddIndex(
            model_name='cockfightmatch',
            index=models.Index(fields=['winTeam'], name='cockfightMa_winTeam_41e8ee_idx'),
        ),
    ]
