# Generated by Django 4.2.7 on 2026-05-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockfightManager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockfightmatchbet',
            name='transactionHash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
