# Generated by Django 4.2.7 on 2026-05-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockfightManager', '0003_cockfightmatchbet_transactionhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cockfightautomatch',
            name='bettingClosedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cockfightautomatch',
            name='bettingOpenedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cockfightautomatch',
            name='liveUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cockfightautomatch',
            name='oddsSnapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cockfightautomatch',
            name='recordingFile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cockfightautomatch',
            name='recordingStatus',
            field=models.CharField(choices=[('none', 'No Recording'), ('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=10),
        ),
    ]
