# Generated by Django 4.2.7 on 2026-03-04 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.storageClasses


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_deposit', models.DecimalField(decimal_places=2, help_text='Minimum deposit to be eligible for a bonus', max_digits=10)),
                ('bonus_value', models.DecimalField(decimal_places=2, help_text='Bonus amount (either percentage or flat)', max_digits=10)),
                ('bonus_type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Flat')], default='F', help_text='Specify if bonus_value is a flat amount or percentage', max_length=1)),
                ('only_first_deposit', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonusDebt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fundsIn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fundsOut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': '5. Wallets',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('withdrawal_type', models.CharField(choices=[('U', 'UPI ID'), ('B', 'Bank Account')], max_length=1)),
                ('withdrawal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('utr_id', models.CharField(blank=True, max_length=100, null=True)),
                ('infoNote', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handling_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': '4. Withdrawal Requests',
            },
        ),
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('qr_image', models.FileField(storage=utility.storageClasses.AzurePublicStorage(), upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_deposit', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment QR',
                'verbose_name_plural': '1. QR Manager',
            },
        ),
        migrations.CreateModel(
            name='PaymentBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_deposit', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Bank Account',
                'verbose_name_plural': '2. Bank Account Manager',
            },
        ),
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenShort', models.FileField(null=True, storage=utility.storageClasses.AzurePublicStorage(), upload_to='paymentScreenshorts/')),
                ('deposit_type', models.CharField(choices=[('Q', 'QR'), ('B', 'Bank Account')], max_length=1)),
                ('utr_id', models.CharField(max_length=100)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirm_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('infoNote', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Request',
                'verbose_name_plural': '3. Deposit Requests',
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('B', 'Bonus'), ('L', 'Lottery'), ('F', 'Cockfight'), ('C', 'Cricket'), ('S', 'Subscription')], max_length=1)),
                ('transactionId', models.CharField(blank=True, max_length=50, null=True)),
                ('change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('isSuccess', models.BooleanField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet History',
                'verbose_name_plural': '7. Wallet History',
                'indexes': [models.Index(fields=['wallet'], name='wallet_wall_wallet__b92706_idx')],
            },
        ),
    ]
