# Generated by Django 4.2.7 on 2026-03-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal'), ('B', 'Bonus'), ('L', 'Lottery'), ('F', 'Cockfight'), ('C', 'Cricket'), ('S', 'Subscription'), ('I', 'Dice Play')], max_length=1),
        ),
    ]
