# Generated by Django 4.2.7 on 2026-05-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallethistory_transactionhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], db_index=True, default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='paymentbankaccount',
            name='min_deposit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='paymentqr',
            name='min_deposit',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], db_index=True, default='P', max_length=1),
        ),
    ]
