# Generated by Django 4.2.7 on 2026-05-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_s3_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusrange',
            options={'ordering': ['min_deposit'], 'verbose_name': 'Bonus Tier', 'verbose_name_plural': '6. Bonus Tiers'},
        ),
        migrations.RenameIndex(
            model_name='depositrequest',
            new_name='wallet_depo_utr_id_8e4829_idx',
            old_name='wallet_dr_utr_id_idx',
        ),
        migrations.RenameIndex(
            model_name='depositrequest',
            new_name='wallet_depo_status_1bcbd1_idx',
            old_name='wallet_dr_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='wallethistory',
            new_name='wallet_wall_wallet__d80b14_idx',
            old_name='wallet_wh_wallet_created_idx',
        ),
        migrations.RenameIndex(
            model_name='wallethistory',
            new_name='wallet_wall_transac_24b8cd_idx',
            old_name='wallet_wh_type_success_idx',
        ),
        migrations.RenameIndex(
            model_name='wallethistory',
            new_name='wallet_wall_created_2596c0_idx',
            old_name='wallet_wh_created_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='withdrawalrequest',
            new_name='wallet_with_status_c5ff72_idx',
            old_name='wallet_wr_status_created_idx',
        ),
        migrations.AlterField(
            model_name='bonusrange',
            name='bonus_type',
            field=models.CharField(choices=[('P', 'Percentage'), ('F', 'Flat')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='bonusrange',
            name='only_first_deposit',
            field=models.BooleanField(default=False, help_text='If true, bonus only applies to first deposit'),
        ),
        migrations.AlterField(
            model_name='paymentbankaccount',
            name='auto_disable_on_limit',
            field=models.BooleanField(default=True, help_text='If checked, auto-disables when daily limit reached and re-enables after 24hrs. Uncheck to keep showing even after limit.'),
        ),
        migrations.AlterField(
            model_name='paymentbankaccount',
            name='daily_credited',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount credited today. Resets automatically after 24hrs.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentbankaccount',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max amount credited via this account in 24hrs. 0 = unlimited.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentbankaccount',
            name='rotation_priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower = shown first.'),
        ),
        migrations.AlterField(
            model_name='paymentqr',
            name='auto_disable_on_limit',
            field=models.BooleanField(default=True, help_text='If checked, auto-disables when daily limit reached and re-enables after 24hrs. Uncheck to keep showing even after limit.'),
        ),
        migrations.AlterField(
            model_name='paymentqr',
            name='daily_credited',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount credited today. Resets automatically after 24hrs.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentqr',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max amount credited via this QR in 24hrs. 0 = unlimited.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentqr',
            name='rotation_priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower = shown first. Auto-rotation cycles through QRs.'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='admin_screenshot',
            field=models.ImageField(blank=True, help_text='Admin uploads payment proof screenshot', null=True, upload_to='withdrawal_proofs/'),
        ),
    ]
