# Generated by Django 4.2.7 on 2026-05-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0002_alter_otpstack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpstack',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='otpstack',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='otpstack',
            index=models.Index(fields=['mobile'], name='userManager_mobile_8e7ac2_idx'),
        ),
    ]
