# Generated by Django 4.2.7 on 2026-03-04 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.storageClasses


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': '1. Dice Boards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DicePlayMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('liveDate', models.DateTimeField(blank=True, null=True)),
                ('isLive', models.BooleanField(default=False)),
                ('isBettingEnabled', models.BooleanField(default=False)),
                ('youtubeLiveLink', models.CharField(blank=True, max_length=100, null=True)),
                ('promoVideo', models.FileField(blank=True, null=True, storage=utility.storageClasses.AzurePublicStorage(), upload_to='dicePlayMatchPromo/')),
                ('total1Rolled', models.PositiveSmallIntegerField(default=0)),
                ('total2Rolled', models.PositiveSmallIntegerField(default=0)),
                ('total3Rolled', models.PositiveSmallIntegerField(default=0)),
                ('total4Rolled', models.PositiveSmallIntegerField(default=0)),
                ('total5Rolled', models.PositiveSmallIntegerField(default=0)),
                ('total6Rolled', models.PositiveSmallIntegerField(default=0)),
                ('isWinnerDeclared', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dicePlayManager.board')),
            ],
            options={
                'verbose_name': 'Dice Play Match',
                'verbose_name_plural': '2. Dice Play Matches',
                'ordering': ['liveDate', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DicePlayMatchBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diceNumber', models.PositiveSmallIntegerField(db_index=True)),
                ('amount', models.PositiveIntegerField()),
                ('matchWinStatus', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('createdDate', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='dicePlayManager.diceplaymatch')),
            ],
            options={
                'verbose_name': 'Dice Play Bet',
                'verbose_name_plural': '3. Dice Play Bets',
                'ordering': ['-createdDate'],
            },
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['is_active'], name='dicePlayMan_is_acti_3e13ff_idx'),
        ),
        migrations.AddIndex(
            model_name='diceplaymatchbet',
            index=models.Index(fields=['match', 'diceNumber'], name='dicePlayMan_match_i_89b2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='diceplaymatchbet',
            index=models.Index(fields=['customer', 'matchWinStatus'], name='dicePlayMan_custome_f1cfba_idx'),
        ),
        migrations.AddIndex(
            model_name='diceplaymatch',
            index=models.Index(fields=['board', 'liveDate'], name='dicePlayMan_board_i_23ad63_idx'),
        ),
        migrations.AddIndex(
            model_name='diceplaymatch',
            index=models.Index(fields=['isLive'], name='dicePlayMan_isLive_d9306e_idx'),
        ),
        migrations.AddIndex(
            model_name='diceplaymatch',
            index=models.Index(fields=['isWinnerDeclared'], name='dicePlayMan_isWinne_bc8723_idx'),
        ),
        migrations.AddIndex(
            model_name='diceplaymatch',
            index=models.Index(fields=['processed'], name='dicePlayMan_process_6434f2_idx'),
        ),
    ]
