# Generated by Django 4.2.7 on 2026-05-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicePlayManager', '0002_diceplaymatchbet_rolled_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='If True, this board runs virtual auto-roll rounds'),
        ),
        migrations.AddField(
            model_name='board',
            name='virtual_betting_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Seconds betting stays open for virtual rounds'),
        ),
        migrations.AddField(
            model_name='diceplaymatch',
            name='dice_result_json',
            field=models.CharField(blank=True, help_text='Individual dice results e.g. 3,3,3,3,5,1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diceplaymatch',
            name='match_type',
            field=models.CharField(choices=[('L', 'Live (Manual)'), ('V', 'Virtual (Auto-Roll)')], default='L', max_length=1),
        ),
        migrations.AddIndex(
            model_name='diceplaymatch',
            index=models.Index(fields=['match_type'], name='dicePlayMan_match_t_cd195e_idx'),
        ),
    ]
