# Generated by Django 4.2.7 on 2026-05-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicePlayManager', '0006_s3_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diceplaymatchbet',
            options={'ordering': ['-createdDate'], 'verbose_name': 'Dice Play Match Bet', 'verbose_name_plural': '3. Dice Play Match Bets'},
        ),
        migrations.RemoveIndex(
            model_name='diceplaymatchbet',
            name='dicePlayMan_match_i_89b2dd_idx',
        ),
        migrations.RenameIndex(
            model_name='diceplaymatch',
            new_name='dicePlayMan_match_d_567f40_idx',
            old_name='diceplaymana_match_d_idx',
        ),
        migrations.RenameIndex(
            model_name='diceplaymatch',
            new_name='dicePlayMan_match_t_089cf0_idx',
            old_name='dice_match_type_winner_idx',
        ),
        migrations.AlterField(
            model_name='diceplaymatch',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diceplaymatchbet',
            name='rolled_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='diceplaymatchbet',
            index=models.Index(fields=['match', 'customer'], name='dicePlayMan_match_i_bad2c0_idx'),
        ),
    ]
